print("What is your name")
print()
name = str(input())
print()
print("What is your age")
print()
age = int(input())
print('what year is it')
print()
yr = int(input())
year = int(100+(yr - age))
print(name,"you wil turn 100 in the year of ",year)
