print ('this is rudra hotel')
print ()
print ('1 adult $50 per night')
print ('18 or younger - $35 per night')
print ('Gaurdians 60+ $30 per night')
print ()
print ('how many days are you going to stay for')
days = int(input())
amount = 0
print ('how many adults')
adults = int(input())
amount +=(50*adults)
print ('how many kids')
kids = int(input())
amount +=(35*kids)
print ('how many guardians')
guardians = int(input())
amount +=(30*guardians)
amount = days * amount
print ('Your Amount is $',amount)
print('Would you like to pay with Credit or Cash')
c= str(input())
if c=='credit':
    print('What are the last 4 digits on the back of your credit card')
    four =int(input())
    print()